"use client"

import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { LayoutDashboard, Library, Layers, ArrowRight, Plus, Minus, FileUp, CreditCard, HelpCircle, BookOpen } from "lucide-react"
import Link from "next/link"
import { useState, useEffect } from "react"
import Navbar from "@/components/navbar";
import { Footer } from "@/components/footer"

export default function TutorMePage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null)
  const [demoStep, setDemoStep] = useState(0)

  useEffect(() => {
    const interval = setInterval(() => {
      setDemoStep((prev) => (prev + 1) % 4)
    }, 2500)
    return () => clearInterval(interval)
  }, [])

  const faqs = [
    {
      question: "What file types can I upload to Tutor Me?",
      answer: "You can upload various formats, including PDF, DOCX, PPTX, and TXT files. You can also import content directly from web links.",
    },
    {
      question: "How are the quizzes and flashcards generated?",
      answer: "Our AI analyzes your uploaded documents to identify key concepts, definitions, and important information to automatically create relevant and effective study materials.",
    },
    {
      question: "Can I edit the materials generated by the AI?",
      answer: "Yes! All generated content, including notes, summaries, flashcards, and quizzes, is fully editable. You can customize them to perfectly fit your study needs.",
    },
    {
      question: "Is there a limit to how many documents I can manage?",
      answer: "Our free plan includes a generous limit, while our premium plans offer unlimited document uploads and storage for your entire academic career.",
    },
  ]
  
  const otherFeatures = [
    { name: "Tutor Me", href: "/features/tutor-me", desc: "Your all-in-one AI study dashboard" },
    { name: "Tutorly Assistant", href: "/features/tutorly-assistant", desc: "Chat with your notes and documents" },
    { name: "AI Content Processor", href: "/features/ai-content-processor", desc: "Scrape websites and YouTube videos" },
    { name: "AI Humanizer", href: "/features/humanizer", desc: "Convert AI text to human-like content" },
    { name: "Math Chat", href: "/features/math-chat", desc: "Solve problems with step-by-step help" },
    { name: "AI Notes", href: "/features/ai-notes", desc: "Generate smart notes from any content" },
  ]

  const demoSteps = [
    { icon: FileUp, text: "Uploaded: Quantum_Physics_Notes.pdf", color: "text-gray-500" },
    { icon: CreditCard, text: "Generating Flashcards...", color: "text-orange-500" },
    { icon: HelpCircle, text: "Building Quiz...", color: "text-rose-500" },
    { icon: BookOpen, text: "Creating Summary...", color: "text-amber-500" },
  ]

  return (
    <div className="min-h-screen bg-white text-black font-mono">
      <Navbar />

      {/* Hero Section */}
      <section className="feature-hero py-20 md:py-32 relative overflow-hidden">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center space-y-8 scroll-fade-in-up">
            <div className="flex justify-center space-x-4 mb-8">
              <div className="w-16 h-16 bg-violet-500 rounded-full flex items-center justify-center brutal-border floating">
                <LayoutDashboard className="w-8 h-8 text-white" />
              </div>
              <div
                className="w-16 h-16 bg-blue-600 rounded-full flex items-center justify-center brutal-border floating"
                style={{ animationDelay: "0.5s" }}
              >
                <Library className="w-8 h-8 text-white" />
              </div>
              <div
                className="w-16 h-16 bg-green-600 rounded-full flex items-center justify-center brutal-border floating"
                style={{ animationDelay: "1s" }}
              >
                <Layers className="w-8 h-8 text-white" />
              </div>
            </div>

            <Badge className="bg-violet-500 text-white font-black text-lg px-6 py-3 brutal-border">
              STUDY HUB
            </Badge>

            <h1 className="text-5xl md:text-7xl font-black leading-none text-black">Tutor Me</h1>

            <p className="text-2xl md:text-3xl font-bold text-violet-700 max-w-4xl mx-auto">
              Your all-in-one AI dashboard to manage documents and generate study tools.
            </p>

            <div className="flex items-center justify-center space-x-4 bg-yellow-100 px-6 py-3 rounded-full brutal-border">
              <LayoutDashboard className="w-6 h-6 text-green-600" />
              <span className="font-black text-lg">Boosts study efficiency by</span>
              <Badge className="bg-yellow-500 text-black font-black px-4 py-2">90%</Badge>
            </div>

            <Link href="/signup">
              <Button className="bg-violet-500 hover:bg-violet-600 text-white font-black text-xl px-12 py-6 brutal-button brutal-button-glow">
                🚀 Create Your Study Hub
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* How It Helps Section */}
      <section className="bg-white py-20">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-16 scroll-fade-in-up">
            <h2 className="text-4xl md:text-6xl font-black mb-6 text-black">One Place for Everything</h2>
            <div className="w-32 h-2 bg-violet-500 mx-auto"></div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {[
              {
                icon: Library,
                title: "UNIFIED WORKSPACE",
                desc: "Upload all your study materials—PDFs, notes, and web links—into one organized, searchable library.",
                bg: "bg-violet-500",
              },
              {
                icon: Layers,
                title: "MULTI-TOOL GENERATION",
                desc: "From any document, instantly generate summaries, flashcards, and practice quizzes with a single click.",
                bg: "bg-blue-600",
              },
              {
                icon: FileUp,
                title: "IMPORT ANYTHING",
                desc: "Easily pull in content from websites or other sources to keep your study hub comprehensive and up-to-date.",
                bg: "bg-green-600",
              },
            ].map((benefit, index) => (
              <div
                key={index}
                className={`${benefit.bg} text-white p-8 brutal-border hover-lift scroll-fade-in-up`}
                style={{ animationDelay: `${index * 0.2}s` }}
              >
                <benefit.icon className="w-16 h-16 mb-6" />
                <h3 className="text-2xl font-black mb-4">{benefit.title}</h3>
                <p className="font-bold leading-relaxed">{benefit.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

     {/* Interactive Demo Section */}
<section className="bg-gray-50 py-20">
  <div className="max-w-6xl mx-auto px-4">
    <div className="text-center mb-16 scroll-fade-in-up">
      <h2 className="text-4xl md:text-6xl font-white mb-6 text-white">
        See Your Hub in Action
      </h2>
      <div className="w-32 h-2 bg-violet-500 mx-auto"></div>
    </div>

    <div className="bg-white brutal-border p-8 interactive-demo">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
        <div className="space-y-6">
          <h3 className="text-2xl font-black">From Document to Study Tools</h3>
          <div className="bg-gray-100 p-6 brutal-border min-h-[200px] flex items-center justify-center">
            <div className="text-center transition-all duration-500 ease-in-out">
              {(() => {
                const StepIcon = demoSteps[demoStep].icon;
                return (
                  <StepIcon
                    className={`w-16 h-16 mx-auto mb-4 ${demoSteps[demoStep].color}`}
                  />
                );
              })()}
              <p className={`text-xl font-black ${demoSteps[demoStep].color}`}>
                {demoSteps[demoStep].text}
              </p>
            </div>
          </div>
        </div>

        <div className="flex items-center justify-center">
          <div className="text-center space-y-6">
            <div className="w-32 h-32 bg-violet-500 rounded-full flex items-center justify-center brutal-border mx-auto">
              <LayoutDashboard className="w-16 h-16 text-white" />
            </div>
            <p className="font-black text-xl text-black">
              Consolidate your learning now!
            </p>
            <Link href="/signup">
              <Button className="bg-violet-500 hover:bg-violet-600 text-white font-black brutal-button">
                Start Building
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

      {/* FAQ Section */}
      <section className="bg-white py-20">
        <div className="max-w-4xl mx-auto px-4">
          <div className="text-center mb-16 scroll-fade-in-up">
            <h2 className="text-4xl md:text-6xl font-black mb-6 text-black">Common Questions</h2>
            <div className="w-32 h-2 bg-violet-500 mx-auto"></div>
          </div>

          <div className="space-y-0">
            {faqs.map((faq, index) => (
              <div
                key={index}
                className="bg-gray-50 brutal-border scroll-fade-in-up"
                style={{ animationDelay: `${index * 0.1}s` }}
              >
                <button
                  className="w-full p-6 text-left flex items-center justify-between font-black text-lg hover:bg-gray-100 transition-colors text-black"
                  onClick={() => setOpenFaq(openFaq === index ? null : index)}
                >
                  {faq.question}
                  <div className={`faq-icon ${openFaq === index ? "open" : ""}`}>
                    {openFaq === index ? <Minus className="w-6 h-6" /> : <Plus className="w-6 h-6" />}
                  </div>
                </button>
                <div className={`faq-content ${openFaq === index ? "open" : ""}`}>
                  <div className="px-6 pb-6">
                    <p className="font-bold text-gray-700">{faq.answer}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

       {/* Other Features */}
      <section className="bg-gray-50 py-20">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-16 scroll-fade-in">
            <h2 className="text-4xl md:text-6xl font-white mb-6 text-white">Explore Other Features</h2>
            <div className="w-32 h-2 bg-blue-600 mx-auto"></div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {otherFeatures.map((feature, index) => (
              <Link key={index} href={feature.href}>
                <div
                  className="bg-white p-6 brutal-border hover-lift hover-scale transition-all cursor-pointer scroll-scale-in"
                  style={{ animationDelay: `${index * 0.1}s` }}
                >
                  <h3 className="text-xl font-black mb-2">{feature.name}</h3>
                  <p className="font-bold text-black-700 mb-4">{feature.desc}</p>
                  <div className="flex items-center justify-between">
                    <span className="font-black text-sm text-purple-600">EXPLORE {feature.name.toUpperCase()}</span>
                    <ArrowRight className="w-4 h-4 text-purple-600" />
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}
